name: friendly_rider


description: "Friendly Rider"


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  http: ^0.13.3
  shared_preferences: ^2.0.6
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.8
  flutter_image_compress: ^2.3.0
#  flutter_vibrate: ^1.3.0
  connectivity_plus: ^2.3.8
  intl: ^0.19.0
  fluttertoast: ^8.2.5
  auto_size_text: ^3.0.0
  dio: ^5.6.0
  http_parser: ^4.0.2
  flutter_otp_text_field: ^1.2.0
  timer_count_down: ^2.2.2
  syncfusion_flutter_datepicker: ^26.2.14
  flutter_floating_bottom_bar: ^1.2.1+1
  fui_kit: ^2.0.0
  text_marquee: ^0.0.2
  marquee: ^2.2.3
  dropdown_button2: ^2.3.9
  iconsax: ^0.0.8
  animated_text_kit: ^4.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

dependency_overrides:
  fading_edge_scrollview: ^4.1.1


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/menu_icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
